---
- name: set timezone to '{{ kxlops_init_timezone }}'
  timezone:
    name: '{{ kxlops_init_timezone }}'
  become: yes
  tags:
    - timezone

- include_tasks: "{{ kxlops_init_os_family }}/main.yml"

- name: Remove PIP packages
  pip: state=absent name={{ item.name }} extra_args={{ item.extra }}
  with_items: '{{ kxlops_init_pip_to_remove }}'
  become: yes
  tags:
    - package-pip-remove

- name: Install PIP packages
  pip: state=present name={{ item.name }} extra_args={{ item.extra }}
  with_items: '{{ kxlops_init_pip_to_install }}'
  become: yes
  tags:
    - package-pip-install

- name: Copy and Execute script
  script: "{{ kxlops_init_script_path }}"
  register: script_output
  when: kxlops_init_script_run

- debug: msg='{{ script_output }}'