---
- name: set timezone to '{{ kxlops_timezone }}'
  timezone:
    name: '{{ kxlops_timezone }}'
  become: yes
  tags:
    - timezone

- name: Cleaning task for yum
  command: /usr/bin/yum clean all
  tags:
    - yumcleanall

- name: Remove unneeded packages
  yum: pkg={{ item }} state=absent
  with_items: '{{ kxlops_init_packages_to_remove }}'
  when: kxlops_init_packages_to_remove | default('false')
  become: yes
  tags:
    - yum-remove

- name: Install packages
  yum: pkg={{ item }} state=present
  with_items: '{{ kxlops_init_packages_to_install }}'
  when: kxlops_init_packages_to_install | default('false')
  become: yes
  tags:
    - yum-install

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  when: kxlops_yum_update_all
  become: yes
  tags:
    - yum-update-all

- name: Install pip packages
  pip:
    name: '{{ item.name }}'
    extra_args: '{{ item.extra }}'
  with_items: '{{ kxlops_init_pip_to_install }}'
  become: yes

- include: config-hostname.yml
  tags:
    - config-hostname
  become: yes
  when: kxlops_init_aws_config

# @TODO work in progress
#- include: config-ec2.yml
#  tags:
#    - config-ec2
#  become: yes
