---
- name: set timezone to '{{ kxlops_init_timezone }}'
  timezone:
    name: '{{ kxlops_init_timezone }}'
  become: yes
  tags:
    - timezone

# OS Tasks

- include: "{{ kxlops_init_os_family }}/main.yml"

- name: Remove PIP packages
  pip: name={{ item.name }} extra_args={{ item.extra }}
  with_items: '{{ kxlops_init_pip_to_remove }}'
  become: yes
  tags:
    - package-install

- name: Install PIP packages
  pip:
    name: '{{ item.name }}'
    extra_args: '{{ item.extra }}'
  with_items: '{{ kxlops_init_pip_to_install }}'
  become: yes

- name: Copy and Execute script
  script: "{{ kxlops_init_script_path }}"
  register: script_output
  when: kxlops_init_script_run

- debug: msg='{{ script_output }}'