---
# Redhat

- name: Cleaning task for YUM
  command: /usr/bin/yum clean all
  tags:
    - yumcleanall

- name: Remove OS packages
  yum: state=absent pkg={{ item }}
  with_items: '{{ kxlops_init_os_to_remove }}'
  when: kxlops_init_os_to_remove | default('false')
  become: yes
  tags:
    - package-remove

- name: Install OS packages
  yum: pkg={{ item }} state=present
  with_items: '{{ kxlops_init_os_to_install }}'
  when: kxlops_init_os_to_install | default('false')
  become: yes
  tags:
    - package-install